### ISSUE TITLE
Publish?

### ISSUE THREAD

**Issue by fuzzy76** [Swift-open-source/UltraTabSaver#5]
![Skjermbilde 2020-05-04 kl  19 28 37](https://user-images.githubusercontent.com/218995/80994797-87294700-8e3d-11ea-9096-2e38e64a331b.png)
![Skjermbilde 2020-05-04 kl  19 28 51](https://user-images.githubusercontent.com/218995/80994804-8a243780-8e3d-11ea-9b22-a3f0cf242bf0.png)

**Comment by Vartkat** [comment]
1 up

**Comment by morsamatias** [comment]
I'm going to publish it as soon as I can.

**Comment by morsamatias** [comment]
Hi, I still didn't have time to upload it to the AppStore, but you can see this [installation guide ](https://github.com/Swift-open-source/UltraTabSaver/blob/main/INSTALLATION_GUIDE.md)

**Comment by drnic1** [comment]
This is great - thanks for putting that together
I will try and report back

**Comment by drnic1** [comment]
Well I got all the way to the end but sadly it requires Catalina and I still cannot upgrade because of the 32/64 bit restriction 
I am hoping to but have some apps I need to replace before I can
Many thanks for the guide

I would add to instructions re the "Signing" which I got past by selecting "Sign to Run Locally" as xCode threw an error

"Signing for "Ultra TabSaver Extension" requires a development team.
Select a development team in the Signing & Capabilities editor."

But tell me if that's not correct

Nick

**Comment by morsamatias** [comment]
@drnic1  Thank you for the feedback, I have added all that specifications to the Installation guide and the macOS Catalina Requirement in the Readme

**Comment by oxyplugins** [comment]
+1 for making this available in Mac App Store.

**Comment by morsamatias** [comment]
Hi @oxyplugins, thanks for your feedback!. I really want to upload it to the App Store but it's pretty expensive, I'm going to upload it as soon as I can afford the Apple Developer Subscription

**Comment by oxyplugins** [comment]
Is that a one-time cost or recurring?

**Comment by morsamatias** [comment]
It's recurring, every year.
[https://developer.apple.com/support/purchase-activation/](https://developer.apple.com/support/purchase-activation/)

**Comment by oxyplugins** [comment]
They should have made it free for free extensions like yours.

Anyway, keep up the good work and thank you for the extension.

**Comment by morsamatias** [comment]
Yes I wish they have free plans to Open Source projects. Thank you for the good vibes, feel free to open any issue with recomendations or other issues to improve the extension.
